(doom!
    <<modulos_Input>>
    <<modulos_Completion>>
    <<modulos_Ui>>
    <<modulos_Editor>>
    <<modulos_Emacs>>
    <<modulos_Term>>
    <<modulos_Checkers>>
    <<modulos_Tools>>
    <<modulos_Os>>
    <<modulos_Lang>>
    <<modulos_Email>>
    <<modulos_App>>
    <<modulos_Config>>
)
